### Test Server
GET https://notes-backend-514828886605.asia-southeast2.run.app/notes

### Tambah Catatan
POST https://notes-backend-514828886605.asia-southeast2.run.app/notes
Content-Type: application/json

{
  "judul": "tes lewat backend",
  "isi": "Ini isi catatan dari REST Client"
}

### Ambil Semua Catatan
GET https://notes-backend-514828886605.asia-southeast2.run.app/notes

### Update Catatan
PUT https://notes-backend-514828886605.asia-southeast2.run.app/notes/1
Content-Type: application/json

{
  "judul": "Catatan Updated lewat backend",
  "isi": "Isi sudah diubah"
}

### Hapus Catatan
DELETE https://notes-backend-514828886605.asia-southeast2.run.app/notes/1